# https://www.designcise.com/web/tutorial/how-to-deploy-to-remote-server-using-ssh-and-github-actions


name: Deployment Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: github_runer_thinhnq
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run file sh
        run: |
          pwd
          whoami
          sh /u01/github_runer_thinhnq.sh